sudo: required

language: python

python:
    - "2.7"

services:
    - docker
    - mysql
    - mongodb
    - redis-server

before_install:
    - docker pull python:2.7
    - docker run -d -p 127.0.0.1:80:4567 python:2.7 /bin/sh -c "cd /root; ls -R; cd /home; ls -R"
    - docker ps -a
    # - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"
    # - mysql -e 'CREATE DATABASE dbaas;'

install:
    - pip install -r requirements_test.txt

cache:
    - pip

before_script:
    - make create_admin_mongo_user

script:
    - make test

notifications:
    email: false
