language: python

python:
    - "2.7"

before_install:
  - mysql -e 'CREATE DATABASE dbaas;'

install:
    - pip install -r requirements_test.txt

services:
    - mysql
    - mongodb
    - redis-server

before_script:
    - mongo admin --eval 'db.createUser( { user: "admin", pwd: "123456", roles: [ "userAdminAnyDatabase", "clusterAdmin", "readWriteAnyDatabase", "dbAdminAnyDatabase" ] } );'

script:
    - make test
