version: '2'

services:
    mysqldb:
        image: mysql:5.6
        environment:
            - MYSQL_ROOT_PASSWORD=123
            - MYSQL_USER=rute
            - MYSQL_PASSWORD=123
            - MYSQL_DATABASE=dbaas
        ports:
            - "3306:3306"

    mysqldb5_7:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=123
            - MYSQL_USER=rute
            - MYSQL_PASSWORD=123
            - MYSQL_DATABASE=dbaas
        ports:
            - "3306:3306"

    mongodb:
        image: mongo:3.4

    redisdb:
        image: redis:3.2

    tests:
        image: dbaas_test
        volumes:
            - .:/code
        depends_on:
            - mysqldb
            - mongodb
            - redisdb
        links:
            - mysqldb
            - mongodb
            - redisdb

        environment:
            - REDIS_HOST=redisdb
            - DBAAS_DATABASE_HOST=db
            - DBAAS_DATABASE_PASSWORD=123
            - TESTS_MONGODB_HOST=mongodb
